package env_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/user/envdiff/internal/env"
	"github.com/user/envdiff/internal/parser"
)

func tempOut(t *testing.T) string {
	t.Helper()
	return filepath.Join(t.TempDir(), ".env.out")
}

func TestClone_WritesAllKeys(t *testing.T) {
	src := map[string]string{"FOO": "bar", "BAZ": "qux"}
	out := tempOut(t)
	if err := env.Clone(src, out, env.DefaultCloneOptions()); err != nil {
		t.Fatalf("Clone: %v", err)
	}
	got, err := parser.ParseFile(out)
	if err != nil {
		t.Fatalf("ParseFile: %v", err)
	}
	for k, v := range src {
		if got[k] != v {
			t.Errorf("key %s: want %q got %q", k, v, got[k])
		}
	}
}

func TestClone_ExcludesKeys(t *testing.T) {
	src := map[string]string{"FOO": "bar", "SECRET": "s3cr3t"}
	out := tempOut(t)
	opts := env.CloneOptions{ExcludeKeys: []string{"SECRET"}}
	if err := env.Clone(src, out, opts); err != nil {
		t.Fatalf("Clone: %v", err)
	}
	got, _ := parser.ParseFile(out)
	if _, ok := got["SECRET"]; ok {
		t.Error("SECRET should have been excluded")
	}
	if got["FOO"] != "bar" {
		t.Errorf("FOO should be present")
	}
}

func TestClone_RedactValues(t *testing.T) {
	src := map[string]string{"FOO": "bar", "BAZ": "qux"}
	out := tempOut(t)
	opts := env.CloneOptions{RedactValues: true}
	if err := env.Clone(src, out, opts); err != nil {
		t.Fatalf("Clone: %v", err)
	}
	got, _ := parser.ParseFile(out)
	for k := range src {
		if got[k] != "" {
			t.Errorf("key %s should be redacted, got %q", k, got[k])
		}
	}
}

func TestClone_Header(t *testing.T) {
	src := map[string]string{"A": "1"}
	out := tempOut(t)
	opts := env.CloneOptions{Header: "generated by envdiff"}
	if err := env.Clone(src, out, opts); err != nil {
		t.Fatalf("Clone: %v", err)
	}
	data, _ := os.ReadFile(out)
	if !strings.Contains(string(data), "# generated by envdiff") {
		t.Error("header not found in output")
	}
}

func TestClone_QuotesSpacedValues(t *testing.T) {
	src := map[string]string{"MSG": "hello world"}
	out := tempOut(t)
	if err := env.Clone(src, out, env.DefaultCloneOptions()); err != nil {
		t.Fatalf("Clone: %v", err)
	}
	data, _ := os.ReadFile(out)
	if !strings.Contains(string(data), `MSG="hello world"`) {
		t.Errorf("expected quoted value, got: %s", string(data))
	}
}
