// Package template generates .env.example files from parsed env maps.
package template

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// Options controls template generation behaviour.
type Options struct {
	// Redact replaces all values with empty strings.
	Redact bool
	// Header is an optional comment written at the top of the file.
	Header string
}

// DefaultOptions returns sensible defaults.
func DefaultOptions() Options {
	return Options{
		Redact: true,
		Header: "# Auto-generated by envdiff. Do not edit manually.",
	}
}

// Generate writes a sorted .env.example to w from the provided env map.
// When opts.Redact is true every value is replaced with an empty string.
func Generate(w io.Writer, env map[string]string, opts Options) error {
	if opts.Header != "" {
		if _, err := fmt.Fprintln(w, opts.Header); err != nil {
			return err
		}
		if _, err := fmt.Fprintln(w); err != nil {
			return err
		}
	}

	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		v := env[k]
		if opts.Redact {
			v = ""
		}
		line := formatLine(k, v)
		if _, err := fmt.Fprintln(w, line); err != nil {
			return err
		}
	}
	return nil
}

// WriteFile generates a template and writes it to the given path.
func WriteFile(path string, env map[string]string, opts Options) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("template: create %s: %w", path, err)
	}
	defer f.Close()
	return Generate(f, env, opts)
}

func formatLine(key, value string) string {
	if value == "" {
		return key + "="
	}
	if strings.ContainsAny(value, " \t#") {
		return fmt.Sprintf(`%s="%s"`, key, value)
	}
	return key + "=" + value
}
